# Generated by Django 5.2.2 on 2025-06-12 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('roll_number', models.CharField(default='Not Assigned', max_length=15, unique=True)),
                ('type', models.CharField(choices=[('Core Member', 'Core Member'), ('Certificate Volunteer', 'Certificate Volunteer'), ('CC Volunteer', 'CC Volunteer')], default='Certificate Volunteer', max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('branch', models.CharField(max_length=50)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('hours', models.FloatField(default=0.0, help_text='Number of hours for the event', verbose_name='Hours')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.event')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.volunteer')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='volunteers',
            field=models.ManyToManyField(related_name='events', through='main.Attendance', to='main.volunteer'),
        ),
        migrations.CreateModel(
            name='AssignedWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(choices=[('Tech', 'Tech'), ('Design', 'Design'), ('Content', 'Content'), ('Logistics', 'Logistics'), ('Social Media', 'Social Media'), ('Public Relations', 'Public Relations'), ('Miscellaneous', 'Miscellaneous')], default='Miscellaneous', max_length=30)),
                ('task', models.TextField()),
                ('hours', models.FloatField(default=0.0, help_text='Number of hours for the work', verbose_name='Hours')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.volunteer')),
            ],
        ),
    ]
