# Generated by Django 5.2.2 on 2025-06-12 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedwork',
            name='assigned_at',
            field=models.DateTimeField(),
        ),
    ]
