# Generated by Django 5.2.2 on 2025-06-12 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_assignedwork_assigned_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedwork',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
