# Generated by Django 5.2.2 on 2025-06-13 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_assignedwork_assigned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedwork',
            name='date',
            field=models.DateField(default='2024-01-01', verbose_name='Date'),
        ),
    ]
