# Generated by Django 5.2.2 on 2025-06-13 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_assignedwork_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedwork',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
