# Generated by Django 5.2.2 on 2025-06-13 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_assignedwork_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedwork',
            name='date',
        ),
    ]
