# Generated by Django 5.2.2 on 2025-06-13 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_assignedwork_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedwork',
            name='date',
            field=models.DateField(default='2023-01-01', help_text='Date when the work is assigned'),
        ),
    ]
